env:
  browser: true
  es2022: true
extends:
  - plugin:vue/recommended
  - standard-with-typescript
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:vuejs-accessibility/recommended
  - plugin:yaml/recommended
  - '@vue/eslint-config-prettier'
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
  createDefaultProgram: true
  project:
    - ./tsconfig.app.json
    - ./tsconfig.node.json
    - ./tsconfig.vitest.json
  extraFileExtensions:
    - .vue
plugins:
  - import
  - tsdoc
  - html
  - yaml
  - vue
rules:
  require-jsdoc: warn
  no-unused-vars: warn
  '@typescript-eslint/ban-ts-comment': off # Enable @ts-ignore etc.
  '@typescript-eslint/consistent-type-imports': # Enable import sort order, see bellow.
    - error
    - prefer: type-imports
  '@typescript-eslint/explicit-function-return-type': off # Fix for pinia
  '@typescript-eslint/no-confusing-void-expression':
    - error
    - ignoreArrowShorthand: true # Allow short land for pretter
  '@typescript-eslint/strict-boolean-expressions': off # Fix for vite import.meta.env
  '@typescript-eslint/triple-slash-reference': off # Fix for vite env.d.ts.
  import/default: off # Fix for Vue setup style
  import/no-default-export: off # Fix for Vue setup style
  import/order: # Sort Import Order. see https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#importorder-enforce-a-convention-in-module-import-order
    - error
    - groups:
        ['builtin', 'external', 'parent', 'sibling', 'index', 'object', 'type']
      pathGroups:
        # Vue Core
        - pattern: '{vue,vue-router,vuex,pinia,vue-i18n,vite,vitest,vitest/**,@vitejs/**,@vue/**,@logue/vue2-helpers,@inertiajs/**,vue-inertia-composable}'
          group: external
          position: before
        # Internal Codes
        - pattern: '{@/plugins/**,@/stores/**,@/router.ts,@/helpers/**,@/interfaces/**,@/types/**,@/components/**,@/views/**}'
          group: internal
          position: before
      pathGroupsExcludedImportTypes:
        - builtin
      alphabetize:
        order: asc
      newlines-between: always
  tsdoc/syntax: warn
  vue/html-self-closing: # A tag with no content should be written like <br />.
    - error
    - html:
        void: always
  vue/multi-word-component-names: warn # Mitigate non-multiword component name errors to warnings.
globals:
  route: true
  Ziggy: readonly
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
    vue-eslint-parser:
      - .vue
  import/resolver:
    typescript: true
    alias:
      map:
        - ['@', './resources/js']
        - ['~', './node_modules']
        - ['ziggy-vue', './vendor/tightenco/ziggy/dist/vue.m']
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
        - .vue
  vite:
    configPath: ./vite.config.ts
